### ISSUE TITLE
No code

### ISSUE THREAD

**Issue by jlian** [FRC4955/Wattson_2015#1]
Where is the code?

**Comment by BrendanFlores** [comment]
We have it on our main laptop but it was in use for most of the day today
so we weren't able to upload it. We have it on drive but there seems to be
an issue on the code we have yet to fix, I'll look into it on Tuesday.

**Comment by cvarier** [comment]
Uploading code is more complicated than simply dragging and dropping files,
as you need to download and install git and get down and dirty with the
command line. We'll definitely need time on Tuesday to do all of this. Do
you know if we're staying past 6?

**Comment by jlian** [comment]
I won't be there and I don't know how long you'll stay. 

Initializing a git repo can be complicated yes, and you made it a bit more difficult by adding the README. 

I would suggest that you `git clone` this repo, then drag and drop all the files into the folder that you just cloned into, then `git commit -am "First commit"` and `git push` 

This way you should be able to avoid having to merge.

**Comment by cvarier** [comment]
OK, I'll try and have the code up tonight.

**Comment by cvarier** [comment]
Alright, code is up.
